/**
 * Prerender the landing page.
 *
 * docs/index.html is a BUILD ARTIFACT, not a file to edit. It is rendered from the same
 * <FeaturesPage /> the app serves at /features, with src/pages/features/features.css inlined
 * verbatim. Edit the component or the stylesheet; run `pnpm run build:landing`.
 *
 * Why bother, rather than keep a hand-written HTML copy: the moment the app has a React
 * landing page AND docs/ has an HTML one, they are two products. The first copy edit lands
 * in one of them and nobody notices for months. A generated file cannot drift.
 *
 * The static output is deliberately near-JS-free. renderToStaticMarkup runs no effects, so:
 *   - the typewriter's initial state is the finished headline (that is why the hook starts
 *     full and erases on mount) — crawlers and no-JS readers get a real <h1>;
 *   - `.reveal` elements would be stuck at opacity:0, so a <noscript> block un-hides them
 *     and a ~12-line inline script drives the observer and the copy button.
 *
 *   Run:  pnpm exec tsx scripts/build-landing.tsx
 */
import { renderToStaticMarkup } from 'react-dom/server';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import React from 'react';
import FeaturesPage from '../src/pages/features/FeaturesPage';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const css = readFileSync(resolve(root, 'src/pages/features/features.css'), 'utf8');
const body = renderToStaticMarkup(React.createElement(FeaturesPage));

const TITLE = 'Piranha — throw a task in, watch the swarm';
const DESC = 'A swarm of AI agents that chews through your backlog — each works in its own sandbox, learns as it goes, and nothing ships without your click. Free, self-hosted, MIT. Runs on your Claude subscription.';
const OG_DESC = 'A swarm of AI agents. Plan → build → QA in isolated worktrees, nothing merges without your click. Free & open source (MIT). Runs on your Claude subscription.';
const FAVICON = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'%3E%3Crect width='100' height='100' rx='22' fill='%230A0E14'/%3E%3Cg fill='%23FF3B1D'%3E%3Cpath d='M18 28 L28 54 L38 28 Z'/%3E%3Cpath d='M36 28 L46 54 L56 28 Z'/%3E%3Cpath d='M54 28 L64 54 L74 28 Z'/%3E%3Cpath d='M27 74 L37 48 L47 74 Z'/%3E%3Cpath d='M45 74 L55 48 L65 74 Z'/%3E%3Cpath d='M63 74 L73 48 L83 74 Z'/%3E%3C/g%3E%3C/svg%3E";

// The only behaviour the static page cannot inherit from React. Reveal + copy; the headline
// is already typed out in the markup above, so no typewriter here.
const ENHANCE = `
(function(){
  var reduce = window.matchMedia && window.matchMedia("(prefers-reduced-motion: reduce)").matches;
  var els = [].slice.call(document.querySelectorAll(".reveal"));
  if ("IntersectionObserver" in window && !reduce) {
    var io = new IntersectionObserver(function(en){
      en.forEach(function(e){ if (e.isIntersecting) { e.target.classList.add("in"); io.unobserve(e.target); } });
    }, { rootMargin: "0px 0px -8% 0px" });
    els.forEach(function(el, i){ el.style.transitionDelay = (Math.min(i % 4, 3) * 55) + "ms"; io.observe(el); });
  } else { els.forEach(function(el){ el.classList.add("in"); }); }

  var btn = document.querySelector(".copybtn");
  if (btn) btn.addEventListener("click", function(){
    var txt = "ANTHROPIC_API_KEY=sk-... docker compose up";
    function ok(){ btn.classList.add("ok"); setTimeout(function(){ btn.classList.remove("ok"); }, 1400); }
    if (navigator.clipboard) navigator.clipboard.writeText(txt).then(ok, function(){});
  });
})();`.trim();

const html = `<!doctype html>
<html lang="en" class="pf-root">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${TITLE}</title>
<meta name="description" content="${DESC}">
<meta name="theme-color" content="#0A0E14">
<meta property="og:title" content="${TITLE}">
<meta property="og:description" content="${OG_DESC}">
<link rel="icon" href="${FAVICON}">
<!-- GENERATED by scripts/build-landing.tsx from src/pages/features/. Do not edit by hand. -->
<style>
*{box-sizing:border-box}
body{margin:0}
${css}
</style>
<noscript><style>.pf .reveal{opacity:1;transform:none}</style></noscript>
</head>
<body>
${body}
<script>${ENHANCE}</script>
</body>
</html>
`;

const out = resolve(root, 'docs/index.html');
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, html, 'utf8');
console.log(`[landing] wrote docs/index.html — ${(html.length / 1024).toFixed(1)} KB, ${html.split('\n').length} lines`);
